# Site settings
name: Thomas Bredillet
title: Welcome
email: thomas@bredillet.com
username: tnbredillet
twitterusername: thomasbredillet
description: "I'm passionate about many things and I want to share a few things with the world."
baseurl: ""
url: "http://www.thomasbredillet.com"

# Build settings
markdown: kramdown
permalinks: pretty
