# Site settings
name: Thomas Bredillet
title: Thomas Bredillet
email: thomas@bredillet.com
username: tnbredillet
twitterusername: thomasbredillet
description: "Thomas Bredillet - Machine Learning, Statistics, Computer Science"
keywords: "thomas bredillet, bredillet, machine learning, statistics, mathematics, systems, programming, recommender system"
baseurl: ""
url: "https://www.thomasbredillet.com"

# Build settings
markdown: kramdown
permalinks: pretty
